name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main
      - CI-CD_pipeline
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    permissions:
        id-token: write
        contents: read
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.ROLE_ARN }}
        role-session-name: github-actions-labsadm
        aws-region: ${{ vars.AWS_REGION }}

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: tf-outputs
        repository: marinaimeninnik/eco-bites-back
       
    - name: Load instance ID from file
      run: cat tf-outputs.env >> $GITHUB_ENV

    - name: Check variables
      run: echo 'bucket_name is ${{ env.FRONTEND_S3_NAME }}'

    - name: Build frontend
      run: npm run build

    # - name: Deploy to S3
    #   run: aws s3 sync ./build s3://${{ env.FRONTEND_S3_NAME }}
    # # env:
    # #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

    # - name: Invalidate CloudFront Distribution
    #   uses: chetan/invalidate-cloudfront-action@v1
    #   env:
    #     DISTRIBUTION: ${{ env.CF_ID }}
    #     PATHS: '/*'
    #     #   AWS_REGION: 'us-west-2'
    #     #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}